# Generated by Django 3.1.3 on 2020-11-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201119_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('fiction', 'fiction'), ('drama', 'drama'), ('history', 'history'), ('children', 'children'), ('college', 'college'), ('biography', 'biography')], max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='home/images')),
                ('rating', models.CharField(max_length=10)),
                ('review', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
