# Generated by Django 3.1.3 on 2020-11-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_orders_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
