# Generated by Django 3.1.3 on 2020-12-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_orderupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='order_id',
        ),
    ]
